### ISSUE TITLE
找不到编译器：wepy-compiler-typescript

### ISSUE THREAD

**Issue by xugege** [vm0100/wepy-plugin-vant#2]

**Comment by xugege** [comment]
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at Module.require (internal/modules/cjs/loader.js:630:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.load (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\loader.js:113:17)
    at Object.loadCompiler (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\loader.js:69:29)
    at Object.compile (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\compile-script.js:242:41)
    at Object.compile (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\compile.js:422:41)
    at D:\develop\work\node\node_global\node_modules\wepy-cli\lib\compile.js:385:47
    at Array.forEach (<anonymous>)
    at Object.build (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\compile.js:379:19)
    at Command.module.exports (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\bin\wepy-build.js:12:21)
    at Command.listener (D:\develop\work\node\node_global\node_modules\wepy-cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (D:\develop\work\node\node_global\node_modules\wepy-cli\node_modules\commander\index.js:651:12)
    at Command.parse (D:\develop\work\node\node_global\node_modules\wepy-cli\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\bin\wepy.js:44:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
[WARNING] 找不到编译器：wepy-compiler-typescript。
[12:15:11] [拷贝] JSON: src\components\vant-weapp\transition\index.json
[12:15:11] [拷贝] WXML: src\components\vant-weapp\transition\index.wxml
[12:15:11] [拷贝] WXSS: src\components\vant-weapp\transition\index.wxss
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at Module.require (internal/modules/cjs/loader.js:630:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.load (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\loader.js:113:17)
    at Object.loadCompiler (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\loader.js:69:29)
    at Object.compile (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\compile-script.js:242:41)
    at Object.compile (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\compile.js:422:41)
    at D:\develop\work\node\node_global\node_modules\wepy-cli\lib\compile.js:385:47
    at Array.forEach (<anonymous>)
    at Object.build (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\compile.js:379:19)
    at Command.module.exports (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\bin\wepy-build.js:12:21)
    at Command.listener (D:\develop\work\node\node_global\node_modules\wepy-cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (D:\develop\work\node\node_global\node_modules\wepy-cli\node_modules\commander\index.js:651:12)
    at Command.parse (D:\develop\work\node\node_global\node_modules\wepy-cli\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (D:\develop\work\node\node_global\node_modules\wepy-cli\lib\bin\wepy.js:44:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

**Comment by vm0100** [comment]
项目中添加typescript编译器即可, npm install --save-dev wepy-compiler-typescript

**Comment by piexl** [comment]
我也遇到同样的问题，安装了wepy-compiler-typescript这个插件还会报错，使用wepy1.7.3

**Comment by vm0100** [comment]
试了下，没问题呀。。。
wepy-cli@1.7.3
然后添加wepy-compiler-typescript生成就没报typescript的错误了呀
